/**
 * All active Princeton departments/programs.
 * Codes from Junction Engine (junction-engine.tigerapps.org).
 * Full names mapped from Princeton's academic catalog.
 */
export const PRINCETON_DEPARTMENTS = [
  { code: "AAS", name: "African American Studies" },
  { code: "AFS", name: "African Studies" },
  { code: "AMS", name: "American Studies" },
  { code: "ANT", name: "Anthropology" },
  { code: "AOS", name: "Atmospheric & Oceanic Sciences" },
  { code: "APC", name: "Applied & Computational Mathematics" },
  { code: "ARA", name: "Arabic" },
  { code: "ARC", name: "Architecture" },
  { code: "ART", name: "Art & Archaeology" },
  { code: "ASA", name: "Asian American Studies" },
  { code: "ASL", name: "American Sign Language" },
  { code: "AST", name: "Astrophysical Sciences" },
  { code: "ATL", name: "Atelier" },
  { code: "BCS", name: "Bosnian-Croatian-Serbian" },
  { code: "BNG", name: "Bengali" },
  { code: "BPY", name: "Biophysics" },
  { code: "CBE", name: "Chemical & Biological Engineering" },
  { code: "CDH", name: "Center for Digital Humanities" },
  { code: "CEE", name: "Civil & Environmental Engineering" },
  { code: "CGS", name: "Cognitive Science" },
  { code: "CHI", name: "Chinese" },
  { code: "CHM", name: "Chemistry" },
  { code: "CHV", name: "Center for Human Values" },
  { code: "CLA", name: "Classics" },
  { code: "CLG", name: "Classical Greek" },
  { code: "COM", name: "Comparative Literature" },
  { code: "COS", name: "Computer Science" },
  { code: "CSE", name: "Computational Science & Engineering" },
  { code: "CWR", name: "Creative Writing" },
  { code: "DAN", name: "Dance" },
  { code: "EAS", name: "East Asian Studies" },
  { code: "ECE", name: "Electrical & Computer Engineering" },
  { code: "ECO", name: "Economics" },
  { code: "ECS", name: "European Cultural Studies" },
  { code: "EEB", name: "Ecology & Evolutionary Biology" },
  { code: "EGR", name: "Engineering" },
  { code: "ENE", name: "Energy Studies" },
  { code: "ENG", name: "English" },
  { code: "ENT", name: "Entrepreneurship" },
  { code: "ENV", name: "Environmental Studies" },
  { code: "EPS", name: "Contemporary European Politics & Society" },
  { code: "FIN", name: "Finance" },
  { code: "FIT", name: "Fitness" },
  { code: "FRE", name: "French" },
  { code: "FRS", name: "Freshman Seminars" },
  { code: "GEO", name: "Geosciences" },
  { code: "GER", name: "German" },
  { code: "GEZ", name: "Ge'ez (Ethiopic)" },
  { code: "GHP", name: "Global Health & Health Policy" },
  { code: "GSS", name: "Gender & Sexuality Studies" },
  { code: "HEB", name: "Hebrew" },
  { code: "HIN", name: "Hindi" },
  { code: "HIS", name: "History" },
  { code: "HLS", name: "Hellenic Studies" },
  { code: "HOS", name: "History of Science" },
  { code: "HUM", name: "Humanities" },
  { code: "ISC", name: "Integrated Science" },
  { code: "ITA", name: "Italian" },
  { code: "JDS", name: "Judaic Studies" },
  { code: "JPN", name: "Japanese" },
  { code: "JRN", name: "Journalism" },
  { code: "KOR", name: "Korean" },
  { code: "LAO", name: "Latino Studies" },
  { code: "LAS", name: "Latin American Studies" },
  { code: "LAT", name: "Latin" },
  { code: "LIN", name: "Linguistics" },
  { code: "MAE", name: "Mechanical & Aerospace Engineering" },
  { code: "MAT", name: "Mathematics" },
  { code: "MED", name: "Medieval Studies" },
  { code: "MOD", name: "Modern & Contemporary Art" },
  { code: "MOG", name: "Modern Greek" },
  { code: "MOL", name: "Molecular Biology" },
  { code: "MPP", name: "Music Performance" },
  { code: "MSE", name: "Materials Science & Engineering" },
  { code: "MTD", name: "Music Theater" },
  { code: "MUS", name: "Music" },
  { code: "NES", name: "Near Eastern Studies" },
  { code: "NEU", name: "Neuroscience" },
  { code: "ORF", name: "Operations Research & Financial Engineering" },
  { code: "PAW", name: "Ancient World" },
  { code: "PER", name: "Persian" },
  { code: "PHI", name: "Philosophy" },
  { code: "PHY", name: "Physics" },
  { code: "PLS", name: "Polish" },
  { code: "POL", name: "Politics" },
  { code: "POP", name: "Population Studies" },
  { code: "POR", name: "Portuguese" },
  { code: "PSY", name: "Psychology" },
  { code: "QCB", name: "Quantitative & Computational Biology" },
  { code: "QSE", name: "Quantum Science & Engineering" },
  { code: "REL", name: "Religion" },
  { code: "RES", name: "Resistance Studies" },
  { code: "ROB", name: "Robotics & Intelligent Systems" },
  { code: "RUS", name: "Russian" },
  { code: "SAN", name: "Sanskrit" },
  { code: "SAS", name: "South Asian Studies" },
  { code: "SLA", name: "Slavic Languages & Literatures" },
  { code: "SML", name: "Statistics & Machine Learning" },
  { code: "SOC", name: "Sociology" },
  { code: "SPA", name: "Spanish" },
  { code: "SPI", name: "School of Public & International Affairs" },
  { code: "SPO", name: "Sports & Athletics" },
  { code: "STC", name: "Science, Technology & Culture" },
  { code: "SWA", name: "Swahili" },
  { code: "THR", name: "Theater" },
  { code: "TPP", name: "Teacher Preparation" },
  { code: "TRA", name: "Translation & Intercultural Communication" },
  { code: "TUR", name: "Turkish" },
  { code: "TWI", name: "Twi" },
  { code: "UKR", name: "Ukrainian" },
  { code: "URB", name: "Urban Studies" },
  { code: "URD", name: "Urdu" },
  { code: "VIS", name: "Visual Arts" },
  { code: "WRI", name: "Writing" },
] as const;

/**
 * Princeton concentrations (majors) students can declare.
 * Departments offering both A.B. and B.S.E. degrees are listed separately.
 */
export const PRINCETON_MAJORS: { code: string; name: string; degree?: string }[] = [
  // ── B.S.E. concentrations ──
  { code: "CBE", name: "Chemical & Biological Engineering", degree: "B.S.E." },
  { code: "CEE", name: "Civil & Environmental Engineering", degree: "B.S.E." },
  { code: "COS-BSE", name: "Computer Science", degree: "B.S.E." },
  { code: "ECE", name: "Electrical & Computer Engineering", degree: "B.S.E." },
  { code: "MAE", name: "Mechanical & Aerospace Engineering", degree: "B.S.E." },
  { code: "MSE", name: "Materials Science & Engineering", degree: "B.S.E." },
  { code: "ORF", name: "Operations Research & Financial Engineering", degree: "B.S.E." },

  // ── A.B. concentrations ──
  { code: "AAS", name: "African American Studies", degree: "A.B." },
  { code: "ANT", name: "Anthropology", degree: "A.B." },
  { code: "ARC", name: "Architecture", degree: "A.B." },
  { code: "ART", name: "Art & Archaeology", degree: "A.B." },
  { code: "AST", name: "Astrophysical Sciences", degree: "A.B." },
  { code: "CHM", name: "Chemistry", degree: "A.B." },
  { code: "CLA", name: "Classics", degree: "A.B." },
  { code: "COM", name: "Comparative Literature", degree: "A.B." },
  { code: "COS-AB", name: "Computer Science", degree: "A.B." },
  { code: "EAS", name: "East Asian Studies", degree: "A.B." },
  { code: "ECO", name: "Economics", degree: "A.B." },
  { code: "EEB", name: "Ecology & Evolutionary Biology", degree: "A.B." },
  { code: "ENG", name: "English", degree: "A.B." },
  { code: "FRE", name: "French & Italian", degree: "A.B." },
  { code: "GEO", name: "Geosciences", degree: "A.B." },
  { code: "GER", name: "German", degree: "A.B." },
  { code: "HIS", name: "History", degree: "A.B." },
  { code: "MAT", name: "Mathematics", degree: "A.B." },
  { code: "MOL", name: "Molecular Biology", degree: "A.B." },
  { code: "MUS", name: "Music", degree: "A.B." },
  { code: "NES", name: "Near Eastern Studies", degree: "A.B." },
  { code: "NEU", name: "Neuroscience", degree: "A.B." },
  { code: "PHI", name: "Philosophy", degree: "A.B." },
  { code: "PHY", name: "Physics", degree: "A.B." },
  { code: "POL", name: "Politics", degree: "A.B." },
  { code: "PSY", name: "Psychology", degree: "A.B." },
  { code: "REL", name: "Religion", degree: "A.B." },
  { code: "SLA", name: "Slavic Languages & Literatures", degree: "A.B." },
  { code: "SOC", name: "Sociology", degree: "A.B." },
  { code: "SPA", name: "Spanish & Portuguese", degree: "A.B." },
  { code: "SPI", name: "School of Public & International Affairs", degree: "A.B." },

  // ── Interdepartmental & certificate programs ──
  { code: "AMS", name: "American Studies" },
  { code: "AFS", name: "African Studies" },
  { code: "APC", name: "Applied & Computational Mathematics" },
  { code: "CGS", name: "Cognitive Science" },
  { code: "CWR", name: "Creative Writing" },
  { code: "DAN", name: "Dance" },
  { code: "EGR", name: "Engineering" },
  { code: "ENV", name: "Environmental Studies" },
  { code: "GHP", name: "Global Health & Health Policy" },
  { code: "GSS", name: "Gender & Sexuality Studies" },
  { code: "LIN", name: "Linguistics" },
  { code: "QCB", name: "Quantitative & Computational Biology" },
  { code: "ROB", name: "Robotics & Intelligent Systems" },
  { code: "SAS", name: "South Asian Studies" },
  { code: "SML", name: "Statistics & Machine Learning" },
  { code: "THR", name: "Theater" },
  { code: "URB", name: "Urban Studies" },
  { code: "VIS", name: "Visual Arts" },
];
